<csv 전처리>

<h1>CSV 전처리</h1>

In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('autos_stata-ed.csv', sep=',')

In [5]:
pd.set_option('display.max_columns', 100)

In [6]:
# df = df.drop(df.loc[:, 'd_seller':'hoursBeforeSale'], axis=1) # stata 뻘짓 지우는 코드. 신경 안 써도 됨.

In [7]:
df.describe()

,price,yearofregistration,powerps,kilometer,monthofregistration,nrofpictures,postalcode
count,3.707520e+05,370752.000000,370752.000000,370752.000000,370752.000000,370752.0,370752.000000
mean,1.729477e+04,2004.570387,115.369767,125666.914811,5.733895,0.0,50812.724250
std,3.591707e+06,92.963304,192.259246,40077.498843,3.713343,0.0,25800.490553
min,0.000000e+00,1000.000000,0.000000,5000.000000,0.000000,0.0,1067.000000
25%,1.150000e+03,1999.000000,69.000000,125000.000000,3.000000,0.0,30457.000000
50%,2.950000e+03,2003.000000,105.000000,150000.000000,6.000000,0.0,49610.000000
75%,7.150000e+03,2008.000000,150.000000,150000.000000,9.000000,0.0,71543.000000
max,2.147484e+09,9999.000000,20000.000000,150000.000000,12.000000,0.0,99998.000000

In [8]:
df.describe(include = "all") # unique로 categorical values 몇 개 인지 확인.

,datecrawled,name,seller,offertype,price,abtest,vehicletype,yearofregistration,gearbox,powerps,model,kilometer,monthofregistration,fueltype,brand,notrepaireddamage,datecreated,nrofpictures,postalcode,lastseen
count,371824,371824,370752,370752,3.707520e+05,370752,332888,370752.000000,350544,370752.000000,350269,370752.000000,370752.000000,337368,370752,298726,370752,370752.0,370752.000000,370752
unique,280652,233736,2,2,NaN,2,8,NaN,2,NaN,251,NaN,NaN,7,40,2,113,NaN,NaN,182618
top,2016-03-24 14:49:47,Ford_Fiesta,privat,Angebot,NaN,test,limousine,NaN,manuell,NaN,golf,NaN,NaN,benzin,volkswagen,nein,2016-04-03 00:00:00,NaN,NaN,2016-04-06 13:45:54
freq,7,657,370749,370740,NaN,192138,95617,NaN,273756,NaN,29972,NaN,NaN,223457,79457,262455,14428,NaN,NaN,17
mean,NaN,NaN,NaN,NaN,1.729477e+04,NaN,NaN,2004.570387,NaN,115.369767,NaN,125666.914811,5.733895,NaN,NaN,NaN,NaN,0.0,50812.724250,NaN
std,NaN,NaN,NaN,NaN,3.591707e+06,NaN,NaN,92.963304,NaN,192.259246,NaN,40077.498843,3.713343,NaN,NaN,NaN,NaN,0.0,25800.490553,NaN
min,NaN,NaN,NaN,NaN,0.000000e+00,NaN,NaN,1000.000000,NaN,0.000000,NaN,5000.000000,0.000000,NaN,NaN,NaN,NaN,0.0,1067.000000,NaN
25%,NaN,NaN,NaN,NaN,1.150000e+03,NaN,NaN,1999.000000,NaN,69.000000,NaN,125000.000000,3.000000,NaN,NaN,NaN,NaN,0.0,30457.000000,NaN
50%,NaN,NaN,NaN,NaN,2.950000e+03,NaN,NaN,2003.000000,NaN,105.000000,NaN,150000.000000,6.000000,NaN,NaN,NaN,NaN,0.0,49610.000000,NaN
75%,NaN,NaN,NaN,NaN,7.150000e+03,NaN,NaN,2008.000000,NaN,150.000000,NaN,150000.000000,9.000000,NaN,NaN,NaN,NaN,0.0,71543.000000,NaN
max,NaN,NaN,NaN,NaN,2.147484e+09,NaN,NaN,9999.000000,NaN,20000.000000,NaN,150000.000000,12.000000,NaN,NaN,NaN,NaN,0.0,99998.000000,NaN

<h1>Date column들 datetime으로 변경. </h1>

In [9]:
for i in ['datecrawled', 'datecreated', 'lastseen']:
    df[i] = pd.to_datetime(df[i], format="%Y-%m-%d %H:%M:%S", errors = 'ignore')

In [10]:
for i in ['datecrawled', 'datecreated', 'lastseen']:
    print(df[i].dtype)

datetime64[ns]
datetime64[ns]
datetime64[ns]

In [11]:
type(df['lastseen'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [12]:
df

,datecrawled,name,seller,offertype,price,abtest,vehicletype,yearofregistration,gearbox,powerps,model,kilometer,monthofregistration,fueltype,brand,notrepaireddamage,datecreated,nrofpictures,postalcode,lastseen
0,2016-03-24 11:52:17,Golf_3_1.6,privat,Angebot,480.0,test,NaN,1993.0,manuell,0.0,golf,150000.0,0.0,benzin,volkswagen,NaN,2016-03-24,0.0,70435.0,2016-04-07 03:16:57
1,2016-03-24 10:58:45,A5_Sportback_2.7_Tdi,privat,Angebot,18300.0,test,coupe,2011.0,manuell,190.0,NaN,125000.0,5.0,diesel,audi,ja,2016-03-24,0.0,66954.0,2016-04-07 01:46:50
2,2016-03-14 12:52:21,"Jeep_Grand_Cherokee_""Overland""",privat,Angebot,9800.0,test,suv,2004.0,automatik,163.0,grand,125000.0,8.0,diesel,jeep,NaN,2016-03-14,0.0,90480.0,2016-04-05 12:47:46
3,2016-03-17 16:54:04,GOLF_4_1_4__3T�RER,privat,Angebot,1500.0,test,kleinwagen,2001.0,manuell,75.0,golf,150000.0,6.0,benzin,volkswagen,nein,2016-03-17,0.0,91074.0,2016-03-17 17:40:17
4,2016-03-31 17:25:20,Skoda_Fabia_1.4_TDI_PD_Classic,privat,Angebot,3600.0,test,kleinwagen,2008.0,manuell,69.0,fabia,90000.0,7.0,diesel,skoda,nein,2016-03-31,0.0,60437.0,2016-04-06 10:17:21
5,2016-04-04 17:36:23,BMW_316i___e36_Limousine___Bastlerfahrzeug__Ex...,privat,Angebot,650.0,test,limousine,1995.0,manuell,102.0,3er,150000.0,10.0,benzin,bmw,ja,2016-04-04,0.0,33775.0,2016-04-06 19:17:07
6,2016-04-01 20:48:51,Peugeot_206_CC_110_Platinum,privat,Angebot,2200.0,test,cabrio,2004.0,manuell,109.0,2_reihe,150000.0,8.0,benzin,peugeot,nein,2016-04-01,0.0,67112.0,2016-04-05 18:18:39
7,2016-03-21 18:54:38,VW_Derby_Bj_80__Scheunenfund,privat,Angebot,0.0,test,limousine,1980.0,manuell,50.0,andere,40000.0,7.0,benzin,volkswagen,nein,2016-03-21,0.0,19348.0,2016-03-25 16:47:58
8,2016-04-04 23:42:13,Ford_C___Max_Titanium_1_0_L_EcoBoost,privat,Angebot,14500.0,control,bus,2014.0,manuell,125.0,c_max,30000.0,8.0,benzin,ford,NaN,2016-04-04,0.0,94505.0,2016-04-04 23:42:13
9,2016-03-17 10:53:50,VW_Golf_4_5_tuerig_zu_verkaufen_mit_Anhaengerk...,privat,Angebot,999.0,test,kleinwagen,1998.0,manuell,101.0,golf,150000.0,0.0,NaN,volkswagen,NaN,2016-03-17,0.0,27472.0,2016-03-31 17:17:06
10,2016-03-26 19:54:18,Mazda_3_1.6_Sport,privat,Angebot,2000.0,control,limousine,2004.0,manuell,105.0,3_reihe,150000.0,12.0,benzin,mazda,nein,2016-03-26,0.0,96224.0,2016-04-06 10:45:34
11,2016-04-07 10:06:22,Volkswagen_Passat_Variant_2.0_TDI_Comfortline,privat,Angebot,2799.0,control,kombi,2005.0,manuell,140.0,passat,150000.0,12.0,diesel,volkswagen,ja,2016-04-07,0.0,57290.0,2016-04-07 10:25:17
12,2016-03-15 22:49:09,"VW_Passat_Facelift_35i__""7Sitzer""",privat,Angebot,999.0,control,kombi,1995.0,manuell,115.0,passat,150000.0,11.0,benzin,volkswagen,NaN,2016-03-15,0.0,37269.0,2016-04-01 13:16:16
13,2016-03-21 21:37:40,VW_PASSAT_1.9_TDI_131_PS_LEDER,privat,Angebot,2500.0,control,kombi,2004.0,manuell,131.0,passat,150000.0,2.0,NaN,volkswagen,nein,2016-03-21,0.0,90762.0,2016-03-23 02:50:54
14,2016-03-21 12:57:01,Nissan_Navara_2.5DPF_SE4x4_Klima_Sitzheizg_Blu...,privat,Angebot,17999.0,control,suv,2011.0,manuell,190.0,navara,70000.0,3.0,diesel,nissan,nein,2016-03-21,0.0,4177.0,2016-04-06 07:45:42
15,2016-03-11 21:39:15,KA_Lufthansa_Edition_450�_VB,privat,Angebot,450.0,test,kleinwagen,1910.0,NaN,0.0,ka,5000.0,0.0,benzin,ford,NaN,2016-03-11,0.0,24148.0,2016-03-19 08:46:47
16,2016-04-01 12:46:46,Polo_6n_1_4,privat,Angebot,300.0,test,NaN,2016.0,NaN,60.0,polo,150000.0,0.0,benzin,volkswagen,NaN,2016-04-01,0.0,38871.0,2016-04-01 12:46:46
17,2016-03-20 10:25:19,Renault_Twingo_1.2_16V_Aut.,privat,Angebot,1750.0,control,kleinwagen,2004.0,automatik,75.0,twingo,150000.0,2.0,benzin,renault,nein,2016-03-20,0.0,65599.0,2016-04-06 13:16:07
18,2016-03-23 15:48:05,Ford_C_MAX_2.0_TDCi_DPF_Titanium,privat,Angebot,7550.0,test,bus,2007.0,manuell,136.0,c_max,150000.0,6.0,diesel,ford,nein,2016-03-23,0.0,88361.0,2016-04-05 18:45:11
19,2016-04-01 22:55:47,Mercedes_Benz_A_160_Classic_Klima,privat,Angebot,1850.0,test,bus,2004.0,manuell,102.0,a_klasse,150000.0,1.0,benzin,mercedes_benz,nein,2016-04-01,0.0,49565.0,2016-04-05 22:46:05
20,2016-04-01 19:56:48,Volkswagen_Scirocco_1.4_TSI_Sport,privat,Angebot,10400.0,control,coupe,2009.0,manuell,160.0,scirocco,100000.0,4.0,benzin,volkswagen,nein,2016-04-01,0.0,75365.0,2016-04-05 16:45:49
21,2016-03-27 11:38:00,BMW_530i_T�V_7/17_Scheckheftgepflegt_sehr_gute...,privat,Angebot,3699.0,test,limousine,2002.0,automatik,231.0,5er,150000.0,7.0,benzin,bmw,nein,2016-03-27,0.0,68309.0,2016-04-07 06:44:26
22,2016-03-23 14:52:51,Opel_Meriva_1.Hand_T�V_3.2018,privat,Angebot,2900.0,test,NaN,2018.0,manuell,90.0,meriva,150000.0,5.0,benzin,opel,nein,2016-03-23,0.0,49716.0,2016-03-31 01:16:33
23,2016-03-12 19:43:07,Stadtflitzer,privat,Angebot,450.0,test,kleinwagen,1997.0,manuell,50.0,arosa,150000.0,5.0,benzin,seat,nein,2016-03-12,0.0,9526.0,2016-03-21 01:46:11
24,2016-03-13 20:40:49,MERCEDES_200E__T�V_04/2016,privat,Angebot,500.0,test,limousine,1990.0,manuell,118.0,andere,150000.0,10.0,benzin,mercedes_benz,ja,2016-03-13,0.0,35390.0,2016-03-13 20:40:49
25,2016-03-18 21:44:09,BMW_530d_touring_Vollausstattung_NAVI,privat,Angebot,2500.0,control,kombi,2002.0,automatik,193.0,5er,150000.0,9.0,diesel,bmw,ja,2016-03-18,0.0,73765.0,2016-03-18 21:44:09
26,2016-03-10 19:38:18,Citroen_C4_Grand_Picasso.,privat,Angebot,5555.0,control,NaN,2017.0,manuell,125.0,c4,125000.0,4.0,NaN,citroen,nein,2016-03-10,0.0,31139.0,2016-03-16 09:16:46
27,2016-03-07 12:51:23,Honda_Civic_1.4_i_VTEC_Comfort,privat,Angebot,6900.0,test,limousine,2008.0,manuell,99.0,civic,60000.0,11.0,benzin,honda,nein,2016-03-07,0.0,12621.0,2016-03-26 09:44:53
28,2016-03-09 11:56:38,Volkswagen_T3_andere,privat,Angebot,1990.0,test,bus,1981.0,manuell,50.0,transporter,5000.0,1.0,benzin,volkswagen,nein,2016-03-09,0.0,87471.0,2016-03-10 07:44:33
29,2016-03-08 19:55:19,Fiat_Punto_1.2,privat,Angebot,690.0,test,kleinwagen,2003.0,manuell,60.0,punto,150000.0,3.0,benzin,fiat,nein,2016-03-08,0.0,86199.0,2016-03-09 11:45:28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371794,2016-03-11 15:50:38,Opel_Vectra_Edition_100,privat,Angebot,699.0,control,limousine,1999.0,manuell,101.0,vectra,150000.0,3.0,benzin,opel,NaN,2016-03-11,0.0,65936.0,2016-03-17 12:44:29
371795,2016-03-08 13:52:00,OPEL_CORSA_B__ECO_SWING__T�V_1/17_8fach_Bereif...,privat,Angebot,600.0,control,kleinwagen,1998.0,manuell,54.0,corsa,150000.0,1.0,benzin,opel,nein,2016-03-08,0.0,24850.0,2016-03-13 00:16:40
371796,2016-03-21 23:40:49,Volkswagen_Golf_1.4_TSI_BlueMotion_Technology_...,privat,Angebot,20400.0,test,limousine,2014.0,automatik,150.0,golf,30000.0,9.0,benzin,volkswagen,nein,2016-03-21,0.0,38470.0,2016-04-07 04:17:32
371797,2016-03-26 18:36:54,Chrysler_Voyager,privat,Angebot,3900.0,test,bus,2003.0,automatik,174.0,voyager,150000.0,7.0,benzin,chrysler,nein,2016-03-26,0.0,34320.0,2016-04-06 09:16:04
371798,2016-04-01 12:59:21,Audi_A4_Avant_1.8,privat,Angebot,1600.0,test,kombi,1998.0,manuell,125.0,a4,150000.0,2.0,benzin,audi,nein,2016-04-01,0.0,34414.0,2016-04-07 09:44:29
371799,2016-04-01 01:55:58,Subaru_Justy_1.3,privat,Angebot,1700.0,control,kleinwagen,1999.0,manuell,68.0,justy,70000.0,11.0,benzin,subaru,nein,2016-03-31,0.0,90439.0,2016-04-07 04:16:26
371800,2016-03-07 17:06:35,220_cdi_Benz,privat,Angebot,2600.0,control,NaN,2005.0,automatik,0.0,c_klasse,150000.0,9.0,NaN,mercedes_benz,NaN,2016-03-07,0.0,61169.0,2016-03-08 21:28:38
371801,2016-04-03 19:56:57,Opel_Astra_1.6_Caravan_Selection,privat,Angebot,800.0,test,kombi,2000.0,manuell,101.0,astra,150000.0,11.0,benzin,opel,ja,2016-04-03,0.0,58730.0,2016-04-05 20:45:39
371802,2016-03-20 18:47:59,Volkswagen_Golf_1.9_TDI_DPF_Goal_Rentnerfzg._1...,privat,Angebot,5900.0,test,limousine,2006.0,manuell,105.0,golf,150000.0,9.0,diesel,volkswagen,nein,2016-03-20,0.0,1217.0,2016-04-07 02:44:27
371803,2016-03-16 17:06:19,Gepflegter_Audi_a4_2.0tdi_xenon_ahk_klima_sche...,privat,Angebot,5999.0,test,kombi,2005.0,manuell,140.0,a4,150000.0,4.0,diesel,audi,NaN,2016-03-16,0.0,56472.0,2016-03-18 11:30:17
371804,2016-04-02 16:43:27,Opel_Astra_1.8,privat,Angebot,1400.0,control,limousine,2001.0,manuell,125.0,astra,150000.0,2.0,benzin,opel,nein,2016-04-02,0.0,23820.0,2016-04-06 15:18:04
371805,2016-03-11 23:40:32,LT_35_DIESEL_Gruene_Plakette....letzte_Gelegen...,privat,Angebot,1900.0,test,NaN,2000.0,manuell,110.0,NaN,150000.0,7.0,NaN,volkswagen,nein,2016-03-11,0.0,87700.0,2016-03-12 14:16:51
371806,2016-03-06 21:11:23,Mercedes_benz_e_klasse_avangarde_220_cdi_grune...,privat,Angebot,6500.0,test,limousine,2003.0,automatik,145.0,e_klasse,150000.0,3.0,diesel,mercedes_benz,nein,2016-03-05,0.0,60437.0,2016-03-12 12:18:05
371807,2016-03-31 18:50:37,Audi_A3_1.8_T_Attraction,privat,Angebot,1999.0,control,limousine,1997.0,manuell,150.0,a3,150000.0,12.0,benzin,audi,nein,2016-03-31,0.0,4275.0,2016-04-06 12:46:41
371808,2016-03-25 18:48:06,Mercedes_Benz_E_400_CDI_Avantgarde,privat,Angebot,5000.0,test,limousine,2003.0,automatik,260.0,e_klasse,150000.0,12.0,diesel,mercedes_benz,ja,2016-03-25,0.0,90473.0,2016-04-07 00:44:51
371809,2016-03-21 15:36:22,Seat_Leon_1.9_TDI_4/5_Tueren,privat,Angebot,4400.0,control,limousine,2008.0,manuell,105.0,leon,150000.0,7.0,diesel,seat,nein,2016-03-21,0.0,45896.0,2016-04-06 15:45:01
371810,2016-04-04 11:45:16,Renault_1_4_ltr.16_V_Megane_Cabrio,privat,Angebot,999.0,control,cabrio,2000.0,manuell,95.0,megane,150000.0,4.0,benzin,renault,NaN,2016-04-04,0.0,88477.0,2016-04-06 12:44:52
371811,2016-03-09 11:36:55,Skoda_Fabia_Kombi_1.4,privat,Angebot,1690.0,test,kombi,2004.0,manuell,55.0,fabia,150000.0,4.0,benzin,skoda,NaN,2016-03-09,0.0,18246.0,2016-04-04 08:15:30
371812,2016-04-04 09:57:12,Volkswagen_Lupo_1.0,privat,Angebot,1490.0,control,kleinwagen,1998.0,manuell,50.0,lupo,150000.0,9.0,benzin,volkswagen,nein,2016-04-04,0.0,48653.0,2016-04-06 11:17:13
371813,2016-03-28 13:48:07,Volkswagen_Golf_2.0_TDI_DPF_Team,privat,Angebot,7900.0,test,limousine,2010.0,manuell,140.0,golf,150000.0,7.0,diesel,volkswagen,nein,2016-03-28,0.0,75223.0,2016-04-02 18:16:20
371814,2016-04-02 20:37:03,Bmw_320_D_DPF_Touring_!!!,privat,Angebot,3999.0,test,kombi,2005.0,manuell,3.0,3er,150000.0,5.0,diesel,bmw,nein,2016-04-02,0.0,81825.0,2016-04-06 20:47:12
371815,2016-03-09 13:37:43,Alfa_Romeo_159_Jtdm_1.9_150_ps_13_600_km_top_voll,privat,Angebot,5250.0,control,NaN,2016.0,automatik,150.0,159,150000.0,12.0,NaN,alfa_romeo,nein,2016-03-09,0.0,51371.0,2016-03-13 01:44:13
371816,2016-03-19 19:53:49,turbo_defekt,privat,Angebot,3200.0,control,limousine,2004.0,manuell,225.0,leon,150000.0,5.0,benzin,seat,ja,2016-03-19,0.0,96465.0,2016-03-19 20:44:43
371817,2016-03-27 20:36:20,Opel_Zafira_1.6_Elegance_T�V_12/16,privat,Angebot,1150.0,control,bus,2000.0,manuell,0.0,zafira,150000.0,3.0,benzin,opel,nein,2016-03-27,0.0,26624.0,2016-03-29 10:17:23
371818,2016-03-21 09:50:58,Mitsubishi_Cold,privat,Angebot,0.0,control,NaN,2005.0,manuell,0.0,colt,150000.0,7.0,benzin,mitsubishi,ja,2016-03-21,0.0,2694.0,2016-03-21 10:42:49
371819,2016-03-14 17:48:27,Suche_t4___vito_ab_6_sitze,privat,Angebot,2200.0,test,NaN,2005.0,NaN,0.0,NaN,20000.0,1.0,NaN,sonstige_autos,NaN,2016-03-14,0.0,39576.0,2016-04-06 00:46:52
371820,2016-03-05 19:56:21,Smart_smart_leistungssteigerung_100ps,privat,Angebot,1199.0,test,cabrio,2000.0,automatik,101.0,fortwo,125000.0,3.0,benzin,smart,nein,2016-03-05,0.0,26135.0,2016-03-11 18:17:12
371821,2016-03-19 18:57:12,Volkswagen_Multivan_T4_TDI_7DC_UY2,privat,Angebot,9200.0,test,bus,1996.0,manuell,102.0,transporter,150000.0,3.0,diesel,volkswagen,nein,2016-03-19,0.0,87439.0,2016-04-07 07:15:26
371822,2016-03-20 19:41:08,VW_Golf_Kombi_1_9l_TDI,privat,Angebot,3400.0,test,kombi,2002.0,manuell,100.0,golf,150000.0,6.0,diesel,volkswagen,NaN,2016-03-20,0.0,40764.0,2016-03-24 12:45:21
371823,2016-03-07 19:39:19,BMW_M135i_vollausgestattet_NP_52.720____Euro,privat,Angebot,28990.0,control,limousine,2013.0,manuell,320.0,m_reihe,50000.0,8.0,benzin,bmw,nein,2016-03-07,0.0,73326.0,2016-03-22 03:17:10

<h1>Categorical values 들어있는 칼럼들 모두 category type으로 변경. </h1>

In [13]:
for i in ['seller', 'offertype', 'abtest', 'vehicletype', 'gearbox', 'model', 'fueltype', 'brand', 'notrepaireddamage' ]:
    df[i] = df[i].astype('category')

<h1> timeBeforeSale = lastseen - datecreated 생성.  </h1>

In [14]:
df["timeBeforeSale"] = (df.lastseen - df.datecreated).astype('timedelta64[ns]')

<h1>csv로 export (지희 R EDA를 위해서)</h>

In [15]:
df.to_csv("df_0521.csv", encoding='utf-8')